# Site settings
title: Technical Game Designer
email: tuplershane5@gmail.com
url: "https://ShaneMakesGames.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/shane-tupler/"
github_url: "https://github.com/ShaneMakesGames/Code-Samples"
twitter_username: MakesShane
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

collections:
  projects:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
